
  n_dim: 128
  hn_dim: 128
  he_dim: 128
  proj_dim: 96

  lr: 0.005
  weight_decay: 1.0e-3

  drop_feature_rate: 0.2
  drop_adj_rate: 0.2
  drop_incidence_rate: 0.1

  tau_n: 0.8
  tau_hn: 0.3
  tau_he: 0.1
  tau_hm: 0.6
  tau_f: 0.5

  w_hn: 1
  w_he: 1
  w_hm: 1
  w_cross: 1
  w_hg: 1

  max_tolerance: 40
  epochs: 1000
